import './globals.css'
import { Nunito_Sans } from 'next/font/google'

const nunito_sans = Nunito_Sans(
  {
    subsets: ['latin']
  }
)

export const metadata = {
  title: 'tutifruti skate',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico',
  },
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={nunito_sans.className}>{children}</body>
    </html>
  )
}
